In [17]:
import sqlite3
import pandas as pd

In [18]:
conn = sqlite3.connect("level_3_final_project_library db")

In [19]:
def run(query):
    return pd.read_sql_query(query, conn)

In [20]:
library_sql_checkouts = pd.read_sql_query("SELECT * FROM checkouts", conn)
library_sql_checkouts.head()

   checkout_id  member_id  book_id checkout_date return_date
0         9263       1047      517    2024-10-21  2024-11-07
1         9340       1072      513    2025-08-24  2025-09-01
2         9231       1053      523    2024-02-04  2024-02-16
3         9129       1032      513    2025-06-21  2025-06-29
4         9370       1079      511    2025-11-11  2025-12-03

In [21]:
library_sql_books = pd.read_sql_query("SELECT * FROM books", conn)
library_sql_books.head()

   book_id                title         author
0      501      The Silver Kite  Amina Darwish
1      502       Desert Compass  Amina Darwish
2      503    The Lantern Maker   Adel Roushdy
3      504  Rooftop Astronomers   Adel Roushdy
4      505  Letters to the Nile      Aya Hafez

In [22]:
library_sql_members = pd.read_sql_query("SELECT * FROM members", conn)
library_sql_members.head()

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date
0,1001,Salma,Ibrahim,8.0,Maadi,Active,2023-04-05
1,1002,Fares,Saleh,9.0,Maadi,Active,None
2,1003,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23
3,1004,Fares,Wahba,7.0,Maadi,inactive,2024-10-09
4,1005,Youssef,Halim,9.0,Maadi,Active,2024-05-05

In [23]:
query = '''
SELECT checkouts.member_id,
       members.first_name,
       members.last_name,
       COUNT(checkouts.member_id) AS checkouts_count

FROM checkouts

JOIN members ON checkouts.member_id = members.member_id

GROUP BY checkouts.member_id
ORDER BY checkouts.member_id DESC
'''

run(query)

    member_id first_name last_name  checkouts_count
0        1080     Bassel     Wahba                2
1        1079       Rana     Osman               10
2        1077       Lina    Rashad                6
3        1076       Dina     Wahba                7
4        1075      Malak     Fahmy                9
..        ...        ...       ...              ...
57       1006      Layla   Mansour                1
58       1005    Youssef     Halim                3
59       1003     Bassel    Hegazy                9
60       1002      Fares     Saleh                2
61       1001      Salma   Ibrahim                1

[62 rows x 4 columns]

In [24]:
query = '''
SELECT author,
       title
FROM books
WHERE title LIKE 'K%'
'''
run(query)

           author             title
0  Jasmine Wahdan  Kites Over Cairo

In [25]:
query = '''
SELECT books.title,
       checkouts.book_id,
       COUNT(checkouts.member_id) AS checkout_count

FROM checkouts

JOIN books ON checkouts.book_id = books.book_id

GROUP BY books.book_id
ORDER BY checkout_count DESC LIMIT 5;

'''
run(query)

                    title  book_id  checkout_count
0         The Silver Kite      501              57
1   Fossils and Fireflies      507              55
2  Circuits for Beginners      513              46
3        Kites Over Cairo      519              38
4    Storms and Sailboats      525              25

In [26]:
query = '''
SELECT books.title,
       checkouts.book_id,
       members.first_name,
       members.last_name,
       members.member_id,
       COUNT(checkouts.member_id) AS checkout_count

FROM checkouts

JOIN books ON checkouts.book_id = books.book_id
JOIN members ON checkouts.member_id = members.member_id

GROUP BY books.book_id
ORDER BY checkout_count DESC LIMIT 10;

'''
run(query)

,title,book_id,first_name,last_name,member_id,checkout_count
0,The Silver Kite,501,Nour,Nabil,1010,57
1,Fossils and Fireflies,507,Mostafa,Fouad,1027,55
2,Circuits for Beginners,513,Seif,Zaki,1072,46
3,Kites Over Cairo,519,Nada,Rashad,1041,38
4,Storms and Sailboats,525,Sherif,Saleh,1044,25
5,The Paper Boat Club,506,Youssef,Hegazy,1024,14
6,Riddles of the Red Sea,529,Mostafa,Fouad,1027,12
7,The Beekeeper's Almanac,516,Lina,Halim,1059,12
8,Marbles and Mirrors,509,Nada,Rashad,1041,9
9,The Last Bookmark,532,Mostafa,Fouad,1027,8

In [27]:
query = '''
SELECT checkouts.book_id,
       members.first_name,
       members.last_name,
       members.member_id,
       members.neighborhood,
       checkouts.checkout_date,
       COUNT(checkouts.member_id) AS checkout_count

FROM checkouts

JOIN books ON checkouts.book_id = books.book_id
JOIN members ON checkouts.member_id = members.member_id

WHERE members.neighborhood = 'Maadi'

GROUP BY checkouts.checkout_date
ORDER BY checkouts.checkout_date DESC LIMIT 10 OFFSET 10;

'''
run(query)

,book_id,first_name,last_name,member_id,neighborhood,checkout_date,checkout_count
0,513,Bassel,Hegazy,1003,Maadi,2025-09-04,1
1,502,Adam,Badr,1017,Maadi,2025-08-25,1
2,501,Ziad,Saleh,1008,Maadi,2025-08-23,1
3,521,Bassel,Hegazy,1003,Maadi,2025-08-21,1
4,525,Ahmed,Shafik,1018,Maadi,2025-08-19,1
5,525,Hamza,Sabry,1015,Maadi,2025-08-08,1
6,503,Ahmed,Shafik,1018,Maadi,2025-08-04,1
7,519,Ziad,Fouad,1013,Maadi,2025-07-27,1
8,513,Bassel,Hegazy,1003,Maadi,2025-07-22,2
9,516,Ziad,Saleh,1008,Maadi,2025-07-20,1

In [28]:
checkouts = run("SELECT * FROM checkouts")
members = run("SELECT * FROM members")

combined = pd.merge(checkouts, members, on='member_id', how='inner')

In [29]:
combined

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27
...,...,...,...,...,...,...,...,...,...,...,...
386,9232,1044,513,2025-05-26,2025-06-11,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19
387,9084,1008,511,2024-06-27,2024-07-22,Ziad,Saleh,8.0,Maadi,active,2025-10-28
388,9116,1024,519,2025-01-10,2025-02-09,Youssef,Hegazy,8.0,Nasr City,inactive,2024-01-04
389,9352,1076,501,2025-02-02,None,Dina,Wahba,7.0,Shubra,Active,2025-12-13
390,9246,1044,529,2025-06-25,2025-07-04,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19

In [30]:
json = pd.read_json("/content/level_3_final_project_library json")
json.head()

   book_id       genre  pages  publication_year            publisher
0      501   Adventure    128            2017.0           Nile Press
1      502   Adventure    109            2018.0          Delta House
2      503  Historical    259               NaN           Nile Press
3      504     Science    319            2009.0  Cairo Young Readers
4      505  Historical    216            2024.0          Oasis Books

In [31]:
book_catalog = pd.merge(combined, json, on='book_id', how='inner')

In [32]:
book_catalog.head()

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher
0,9263,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,Mystery,338,2015.0,Delta House
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books
3,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books
4,9370,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,Historical,117,2016.0,Nile Press

In [33]:
data_unifaction = pd.read_html("/content/level_3_final_project_library html")[0]
data_unifaction.head()

   Member ID  Book ID Checkout Date
0       1026      522    2025-07-11
1       1049      520    2025-07-11
2       1062      525    2025-07-05
3       1065      520    2025-07-07
4       1104      515    2025-07-07

In [34]:
data_unifaction.head()

   Member ID  Book ID Checkout Date
0       1026      522    2025-07-11
1       1049      520    2025-07-11
2       1062      525    2025-07-05
3       1065      520    2025-07-07
4       1104      515    2025-07-07

In [35]:
data_unifaction.columns = ["member_id", "book_id", "checkout_date"]
final_combined = pd.merge(book_catalog, data_unifaction, on='book_id', how='inner')
final_combined

,checkout_id,member_id_x,book_id,checkout_date_x,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher,member_id_y,checkout_date_y
0,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1005,2025-07-10
1,9340,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1061,2025-07-06
2,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1029,2025-07-09
3,9231,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1201,2025-07-08
4,9129,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books,1005,2025-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,9018,1003,522,2025-06-12,2025-06-24,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,Mystery,104,2016.0,Cairo Young Readers,1063,2025-07-07
340,9232,1044,513,2025-05-26,2025-06-11,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,Science,294,2021.0,Oasis Books,1005,2025-07-10
341,9232,1044,513,2025-05-26,2025-06-11,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,Science,294,2021.0,Oasis Books,1061,2025-07-06
342,9084,1008,511,2024-06-27,2024-07-22,Ziad,Saleh,8.0,Maadi,active,2025-10-28,Historical,117,2016.0,Nile Press,1022,2025-07-12
343,9352,1076,501,2025-02-02,None,Dina,Wahba,7.0,Shubra,Active,2025-12-13,Adventure,128,2017.0,Nile Press,1003,2025-07-08

In [36]:
final_combined.drop("checkout_date_x", axis=1, inplace=True)
final_combined.drop("member_id_x", axis=1, inplace=True)

In [37]:
final_combined.columns = ["checkout_id", "book_id", "return_date", "first_name", "last_name", "grade", "neighborhood", "membership_status", "join_date", "genre", "pages", "publication_year", "publisher", "member_id", "checkout_date"]
final_combined.head()

,checkout_id,book_id,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher,member_id,checkout_date
0,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1005,2025-07-10
1,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1061,2025-07-06
2,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1029,2025-07-09
3,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1201,2025-07-08
4,9129,513,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books,1005,2025-07-10

In [38]:
final_combined.shape

(344, 15)

In [39]:
final_combined.head()

,checkout_id,book_id,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher,member_id,checkout_date
0,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1005,2025-07-10
1,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1061,2025-07-06
2,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1029,2025-07-09
3,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1201,2025-07-08
4,9129,513,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books,1005,2025-07-10

In [40]:
final_combined.isna().sum()

checkout_id           0
book_id               0
return_date          66
first_name            0
last_name             0
grade                32
neighborhood          0
membership_status     0
join_date             4
genre                 0
pages                 0
publication_year      8
publisher             0
member_id             0
checkout_date         0
dtype: int64

In [41]:
final_combined["return_date"]=final_combined["return_date"].fillna(final_combined["return_date"].mode()[0])
final_combined["grade"]=final_combined["grade"].fillna(final_combined["grade"].median())
final_combined["join_date"]=final_combined["join_date"].fillna(final_combined["join_date"].mode()[0])
final_combined["publication_year"]=final_combined["publication_year"].fillna(final_combined["publication_year"].mode()[0])

In [42]:
final_combined.isna().sum()

checkout_id          0
book_id              0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
genre                0
pages                0
publication_year     0
publisher            0
member_id            0
checkout_date        0
dtype: int64

In [43]:
final_combined.duplicated().sum()

np.int64(5)

In [44]:
final_combined[final_combined.duplicated()]

,checkout_id,book_id,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher,member_id,checkout_date
198,9296,501,2025-01-11,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,Adventure,128,2017.0,Nile Press,1003,2025-07-08
268,9334,507,2026-01-05,Adam,Fahmy,6.0,Zamalek,Active,2025-07-12,Science,160,2024.0,Nile Press,1017,2025-07-11
294,9194,513,2024-10-09,Youssef,Hegazy,8.0,Nasr City,inactive,2024-01-04,Science,294,2021.0,Oasis Books,1005,2025-07-10
295,9194,513,2024-10-09,Youssef,Hegazy,8.0,Nasr City,inactive,2024-01-04,Science,294,2021.0,Oasis Books,1061,2025-07-06
320,9052,501,2024-06-29,Mostafa,Wahba,6.0,Maadi,Inactive,2024-07-20,Adventure,128,2017.0,Nile Press,1003,2025-07-08

In [45]:
final_combined=final_combined.drop_duplicates()

In [46]:
final_combined.duplicated().sum()

np.int64(0)

In [47]:
final_combined.to_csv("task1_combined_data.csv", index=False)

In [48]:
final_combined.isna().sum()

checkout_id          0
book_id              0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            0
genre                0
pages                0
publication_year     0
publisher            0
member_id            0
checkout_date        0
dtype: int64

In [49]:
final_combined.isna().sum().sum()

np.int64(0)

In [50]:
final_combined.duplicated().sum()

np.int64(0)

In [51]:
df = pd.read_csv("/content/task1_combined_data.csv")
df

,checkout_id,book_id,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher,member_id,checkout_date
0,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1005,2025-07-10
1,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1061,2025-07-06
2,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1029,2025-07-09
3,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1201,2025-07-08
4,9129,513,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books,1005,2025-07-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,9018,522,2025-06-24,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,Mystery,104,2016.0,Cairo Young Readers,1063,2025-07-07
335,9232,513,2025-06-11,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,Science,294,2021.0,Oasis Books,1005,2025-07-10
336,9232,513,2025-06-11,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,Science,294,2021.0,Oasis Books,1061,2025-07-06
337,9084,511,2024-07-22,Ziad,Saleh,8.0,Maadi,active,2025-10-28,Historical,117,2016.0,Nile Press,1022,2025-07-12
338,9352,501,2026-01-05,Dina,Wahba,7.0,Shubra,Active,2025-12-13,Adventure,128,2017.0,Nile Press,1003,2025-07-08

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   checkout_id        339 non-null    int64
 1   book_id            339 non-null    int64
 2   return_date        339 non-null    object
 3   first_name         339 non-null    object
 4   last_name          339 non-null    object
 5   grade              339 non-null    float64
 6   neighborhood       339 non-null    object
 7   membership_status  339 non-null    object
 8   join_date          339 non-null    object
 9   genre              339 non-null    object
 10  pages              339 non-null    int64
 11  publication_year   339 non-null    float64
 12  publisher          339 non-null    object
 13  member_id          339 non-null    int64
 14  checkout_date      339 non-null    object
dtypes: float64(2), int64(4), object(9)
memory usage: 39.9+ KB

In [53]:
df["neighborhood"].value_counts()

neighborhood
Maadi         85
Nasr City     76
Heliopolis    73
Zamalek       58
Shubra        24
Maadi         14
zamalek        7
NASR CITY      1
HELIOPOLIS     1
Name: count, dtype: int64

In [54]:
df.shape

(339, 15)

In [55]:
df["neighborhood"]=df["neighborhood"].str.title().str.strip()

In [56]:
df["neighborhood"].value_counts()

neighborhood
Maadi         99
Nasr City     77
Heliopolis    74
Zamalek       65
Shubra        24
Name: count, dtype: int64

In [57]:
df['membership_status'].value_counts()

membership_status
Active      234
Inactive     45
active       40
inactive     20
Name: count, dtype: int64

In [58]:
df['membership_status'] = df['membership_status'].str.title().str.strip()

In [59]:
df['membership_status'].value_counts()

membership_status
Active      274
Inactive     65
Name: count, dtype: int64

In [60]:
df.shape

(339, 15)

In [61]:
inactive_df = df[df['membership_status'] == 'Inactive']
len(inactive_df)

65

In [62]:
inactive_members_status_by_id = inactive_df.groupby('member_id')['membership_status'].unique()
print(inactive_members_status_by_id)

member_id
1003    [Inactive]
1005    [Inactive]
1007    [Inactive]
1009    [Inactive]
1012    [Inactive]
1017    [Inactive]
1022    [Inactive]
1026    [Inactive]
1049    [Inactive]
1058    [Inactive]
1061    [Inactive]
1062    [Inactive]
1063    [Inactive]
1065    [Inactive]
1073    [Inactive]
1150    [Inactive]
1201    [Inactive]
Name: membership_status, dtype: object

In [63]:
df.to_csv("task2_cleaned_data.csv", index=False)

In [64]:
df = pd.read_csv("/content/task2_cleaned_data.csv")
df.head()

,checkout_id,book_id,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,genre,pages,publication_year,publisher,member_id,checkout_date
0,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1005,2025-07-10
1,9340,513,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Science,294,2021.0,Oasis Books,1061,2025-07-06
2,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1029,2025-07-09
3,9231,523,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Historical,276,2018.0,Oasis Books,1201,2025-07-08
4,9129,513,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Science,294,2021.0,Oasis Books,1005,2025-07-10

In [65]:
neighborhood_by_members = df.groupby('neighborhood')['member_id'].nunique()
print("neighborhood_by_members\n\n", neighborhood_by_members)

neighborhood_by_members

 neighborhood
Heliopolis    19
Maadi         19
Nasr City     19
Shubra        10
Zamalek       16
Name: member_id, dtype: int64

In [66]:
neighborhood_by_checkouts = df.groupby('neighborhood')['checkout_id'].nunique()
print("neighborhood_by_checkouts\n\n", neighborhood_by_checkouts)

neighborhood_by_checkouts

 neighborhood
Heliopolis    55
Maadi         75
Nasr City     61
Shubra        21
Zamalek       48
Name: checkout_id, dtype: int64